### ISSUE TITLE
NameError: name 'wholedata' is not defined

### ISSUE THREAD

**Issue by xinfu607** [vita-epfl/RRB#8]
Hi, some issues happen when running bash run.sh. Could you please tell me the reason ? Thanks a lot.

Traceback (most recent call last):
  File "/opt/conda/envs/py36/lib/python3.6/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)
  File "/opt/conda/envs/py36/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/trajectory_prediction/RRB/trajnetbaselines/trajnetbaselines/trainer.py", line 638, in <module>

    main()
  File "/root/trajectory_prediction/RRB/trajnetbaselines/trajnetbaselines/trainer.py", line 633, in main

    trainer.loop(train_scenes, val_scenes, output_dir, epochs=args.epochs)
  File "/root/trajectory_prediction/RRB/trajnetbaselines/trajnetbaselines/trainer.py", line 65, in loop

    if (epoch % 2 == 0 and wholedata):
NameError: name 'wholedata' is not defined

**Comment by MohammadHossein-Bahari** [comment]
Hello,
It was an unnecessary condition. Simply remove "wholedata". I have updated the code as well.
